# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  postfix:
    type: files
    directory: postfix.d
    # kind: ConfigMap
  postfix-tls:
    type: tls
    directory: postfix.tls
    # existingName: my-postfix-tls
    # cert-manager:
    #   commonName: example.com
    #   issuerRef:
    #     kind: ClusterIssuer
    #     name: letsencrypt-production
  opendkim:
    type: files
    directory: opendkim
  opendkim-keys:
    type: files
    directory: opendkim.keys
  users:
    type: files
    directory: users.d
  yaml:
    type: files
    directory: yaml.d
  env:
    type: env

# /var/spool/postfix
persistence:
  enabled: false
  existingClaim: ""
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

startupProbe:
  tcpSocket:
    port: smtpd
  periodSeconds: 3
  failureThreshold: 10

livenessProbe:
  # tcpSocket:
  #   port: 587
  exec:
    command: ["postfix", "status"]
    # command:
    #   - sh
    #   - -c
    #   - '! /usr/libexec/postfix/master -t'
  initialDelaySeconds: 30
  periodSeconds: 60
  failureThreshold: 1

replicaCount: 1

image:
  repository: insios/smarthost
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  create: true
  type: ClusterIP
  port: 587
  # nodePort: 30587
  # externalTrafficPolicy: Local

servicePP:
  create: false
  type: ClusterIP
  port: 586
  # nodePort: 30586

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Additional ENV on the output Deployment definition.
envFrom: []
# - secretRef:
#     name: mysecret

nodeSelector: {}

tolerations: []

affinity: {}
