{{- define "chart.persistence" }}
{{- if .Values.persistence.enabled }}

{{- if not .Values.persistence.existingClaim }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "chart.fullname" . }}-spool
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}

{{- $_ := set $.Values "volumeMounts" (append $.Values.volumeMounts (dict
  "name" "spool"
  "mountPath" "/var/spool/postfix"
)) }}
{{- $_ := set $.Values "volumes" (append $.Values.volumes (dict
  "name" "spool"
  "persistentVolumeClaim" (dict
    "claimName" (.Values.persistence.existingClaim | default (print (include "chart.fullname" .) "-spool"))
  )
)) }}

{{- end }}
{{- end }}
